
export const ITEMLIST_REQUEST = "ITEMLIST_REQUEST";
export const ITEMLIST_SUCCESS = "ITEMLIST_SUCCESS";
export const ITEMLIST_FAILURE = "ITEMLIST_FAILURE";

export const ITEMADD_REQUEST = "ITEMADD_REQUEST";
export const ITEMADD_SUCCESS = "ITEMADD_SUCCESS";
export const ITEMADD_FAILURE = "ITEMADD_FAILURE";

export const ITEMTRASH_REQUEST = "ITEMTRASH_REQUEST";
export const ITEMTRASH_SUCCESS = "ITEMTRASH_SUCCESS";
export const ITEMTRASH_FAILURE = "ITEMTRASH_FAILURE";